### ISSUE TITLE
https://studio.nearprotocol.com

### ISSUE THREAD

**Issue by inbrains1** [nearprotocol/NEARStudio#125]
Trying to RUN the hello world example output an error as shown below:
![image](https://user-images.githubusercontent.com/36745936/56755884-2af70600-6799-11e9-95f0-a60ec615e73e.png)

**Comment by vgrichina** [comment]
@inbrains1 try refreshing the page, waiting for "AssemblyScript compiler is ready!" message and running again. Sorry for inconvenience, I thought this was fixed with https://github.com/nearprotocol/NEARStudio/pull/119

**Comment by vgrichina** [comment]
Must be fixed now
