### ISSUE TITLE
Error reporting from nearmint calls is broken

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/NEARStudio#127]
Error message
AppActions.ts:339 Unexpected error: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
(This particular error is easily reproducible while trying to access an account that doesn't exist in nearstudio)

**Comment by vgrichina** [comment]
@janedegtiareva this one needs to be merged, fixes most error cases: https://github.com/nearprotocol/nearcore/pull/926

there is remaining similar one https://github.com/nearprotocol/nearlib/issues/1
