### ISSUE TITLE
Bug/ HelloWorld example in AssemblyScript

### ISSUE THREAD

**Issue by kimlisa** [nearprotocol/NEARStudio#138]
Link located in [Writing Contracts](https://docs.nearprotocol.com/working-smart-contracts/writing-contracts#contracts) docs

## How to Reproduce
1. In Chrome, open [Hello World](https://studio.nearprotocol.com/?f=67o8yzfco) 
1. Click Run
1. Error message appears:
![Screen Shot 2019-07-30 at 10 17 03 PM](https://user-images.githubusercontent.com/43280172/62185570-d8893080-b317-11e9-87d0-93d272918e9e.png)

1. Clicked OK, otherwise I had no other way to run the example
1. CORS policy issue prevents fetching "hello world"
![Screen Shot 2019-07-30 at 10 18 34 PM](https://user-images.githubusercontent.com/43280172/62185672-374eaa00-b318-11e9-9104-a29d3352901d.png)

**Comment by janedegtiareva** [comment]
Only happens on old fiddles.
