### ISSUE TITLE
Error: Example of NEAR Wallet integration

### ISSUE THREAD

**Issue by pkrasam** [nearprotocol/NEARStudio#150]
Getting error when trying the 1st sample contract using Studio

[Example of NEAR Wallet integration](https://studio.nearprotocol.com/?f=c41iy5w79)

Both `Run` and `Test` gives an error

Error:

> Unexpected error: Error: 400: Error: Transaction 37FUAzyTqp47dFfnNXZQ3hTewBComNk8vSpk145L15Fo failed. Runtime error: Account studio-c41iy5w79 already exists

**Comment by vgrichina** [comment]
@pkrasam I tried forking and running link above and it worked for me. Looks like some temporary glitch, may you also try doing a Fork and then running again?

**Comment by janedegtiareva** [comment]
This fiddle has a contract which is using old version of runtime. We are not supporting it anymore.
