### ISSUE TITLE
Files view tree is laggy

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/NEARStudio#156]
If I collapse any(or all folders) on the left and then click on any file the entire tree expands (it is however inconsistent and expands only partially). See: 
https://www.dropbox.com/s/jdmbqsu8i9k6d7t/NearStudio%20laggy%20tree.mov?dl=0

**Comment by vgrichina** [comment]
this is known issue https://github.com/nearprotocol/NEARStudio/issues/18
