### ISSUE TITLE
Editor file tree expands automatically in annoying manner

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/NEARStudio#18]
Tree should only expand when:
1) it's expanded by user
2) file inside of collapsed folder is opened

**Comment by ailisp** [comment]
This is still an issue as of now. When user open one file, it expand all nodes. It's also an issue of upstream wasm studio so we'd probably want to fix there too.

**Comment by vgrichina** [comment]
@ailisp upstream wasm not really maintained, we are diverging from it

**Comment by vgrichina** [comment]
I haven't digged into this bug yet as it wasn't a problem before we added too many files into templates )

**Comment by janedegtiareva** [comment]
I am going to take a look.
