### ISSUE TITLE
Run NEARStudio with local middleware

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/NEARStudio#43]
Add a flag to specify where middleware runs

**Comment by janedegtiareva** [comment]
added a config value https://github.com/nearprotocol/NEARStudio/pull/44

**Comment by ilblackdragon** [comment]
Should modify contractHelper to only be `https://studio.nearprotocol.com/contract-api/` and then different endpoints (`/contract/` or `/account/name`) can be attached to it.

**Comment by vgrichina** [comment]
Fixed here:
https://github.com/nearprotocol/NEARStudio/commit/b6657f9ed7d261491e71a93850a89ce65923f99d
