### ISSUE TITLE
Token contract

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/NEARStudio#6]

**Comment by ilblackdragon** [comment]
Token contract currently doesn't work, because _init is not allowed anymore.

Also on the `master` `templates` folder doesn't have current templates.

**Comment by vgrichina** [comment]
> Also on the `master` `templates` folder doesn't have current templates.

@ilblackdragon may you be more specific? Do you mean it's out of sync with docs?

**Comment by vgrichina** [comment]
@ilblackdragon 
Updated templates to avoid using `_init`. Re-open if anything else is needed.
