### ISSUE TITLE
[AS] Failed to encode u64

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/NEARStudio#90]
If you use u64 types as part of the model, e.g.:
```
export class Mess {
  sender: string;
  timeMs: i64;
}
```

Compiler complains:
```
ERROR TS2304: Cannot find name '__near_encode_u64'.

           __near_encode_u64(<u64>value.timeMs, encoder);
           ~~~~~~~~~~~~~~~~~
 in model.near.ts(26,10)
```

**Comment by evgenykuzyakov** [comment]
Same for i64

**Comment by vgrichina** [comment]
@evgenykuzyakov we cannot really encode them as JSON numbers (JS only has 53-bit precision).
I can add code to serialize into JSON strings. WDYT?

**Comment by evgenykuzyakov** [comment]
Oh I see. I guess we have to do strings.

**Comment by evgenykuzyakov** [comment]
Actually it would be better to just ignore JSON spec and use long numbers.

**Comment by vgrichina** [comment]
@evgenykuzyakov no, cause then it would fail in browsers and in a subtle and dangerous way (numbers rounded to 53-bit precision)
