### ISSUE TITLE
When using someone else fiddle, both "Run" and "Test" should fork first.

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/NEARStudio#93]
Currently, it's failing since you can't redeploy the existing contract which is owned by someone else.

**Comment by potatodepaulo** [comment]
What if when you land on code deployed by a different author, there is some link to the already deployed app and run/test are disabled? All the steps to get there would be the same as above, but this way would allow you to interact with whatever state they have.

**Comment by evgenykuzyakov** [comment]
It should be easy to fix, do it @potatodepaulo

**Comment by potatodepaulo** [comment]
@vgrichina This is the studio task I mentioned
