### ISSUE TITLE
When I try to run Todo app I get:

### ISSUE THREAD

**Issue by billp72** [nearprotocol/NEARStudio#98]
Failed to load resource: net::ERR_CONNECTION_RESET
app.js:23 Uncaught ReferenceError: Vue is not defined
    at app.js:23
    at app.js:144

**Comment by vgrichina** [comment]
@billp72 what browser do you use? Do I assume correctly that you start from TodoMVC template NEAR Studio offers?

**Comment by billp72** [comment]
It was down for a couple of hours yesterday. Today, I completely closed my
Chrome browser and rebooted my machine and it came back up. Just one of
those things, I guess.

Yes, I was using the TodoMVC template.

Thanks, Bill

**Comment by vgrichina** [comment]
@billp72 I see, might have been temporary CDN problem. Feel free to re-open if issue occurs again.
